"""Add output_video_path and model_name fields to Video table

Revision ID: a8e34ea9d9ca
Revises: 
Create Date: 2025-10-27 21:39:25.002777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e34ea9d9ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_file_name', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('output_video_path', sa.String(length=255), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('empty_count', sa.Integer(), nullable=True),
    sa.Column('empty_ls_count', sa.Integer(), nullable=True),
    sa.Column('hb_count', sa.Integer(), nullable=True),
    sa.Column('hb_ls_count', sa.Integer(), nullable=True),
    sa.Column('hb_ab_count', sa.Integer(), nullable=True),
    sa.Column('unripe_count', sa.Integer(), nullable=True),
    sa.Column('unripe_ls_count', sa.Integer(), nullable=True),
    sa.Column('unripe_ab_count', sa.Integer(), nullable=True),
    sa.Column('ripe_count', sa.Integer(), nullable=True),
    sa.Column('ripe_ls_count', sa.Integer(), nullable=True),
    sa.Column('ripe_ab_count', sa.Integer(), nullable=True),
    sa.Column('overripe_count', sa.Integer(), nullable=True),
    sa.Column('overripe_ls_count', sa.Integer(), nullable=True),
    sa.Column('overripe_ab_count', sa.Integer(), nullable=True),
    sa.Column('bunch_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    # ### end Alembic commands ###
